# FPL Machine Learning: Binary Classification problem

In [419]:
#Fantasy Premier League machine learning project applying what I learnt while studying the Iris dataset.
#The aim will be to produce a model which can predict whether a given player has performed above or below average.
#I will be using the data set 'cleaned_players.csv' by Vaastav which I scraped from github.
#

In [420]:
#First lets import our dependancies and have a look at the data.
import pandas as pd
import numpy as np
import io
import requests
url = 'https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2019-20/cleaned_players.csv'
read_data = requests.get(url).content
print(read_data)

b"first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost\r\nShkodran,Mustafi,0,2,19,440,7,13.2,128.8,79.0,1,101,22.2,1,0,0,0.3,51\r\nH\xc3\xa9ctor,Beller\xc3\xadn,1,0,17,442,8,28.1,103.8,28.0,3,81,16.1,1,0,2,0.8,54\r\nSead,Kolasinac,0,2,34,1086,18,156.3,190.0,67.0,1,219,41.2,2,0,3,0.5,52\r\nAinsley,Maitland-Niles,0,2,36,1210,19,155.4,261.8,37.0,3,216,44.9,3,1,3,2.5,46\r\nSokratis,Papastathopoulos,2,0,52,1606,25,31.8,431.6,106.0,5,286,57.1,3,0,5,1.4,49\r\nNacho,Monreal,0,0,10,270,4,40.8,47.2,12.0,1,54,10.0,1,0,0,0.2,50\r\nLaurent,Koscielny,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,50\r\nKonstantinos,Mavropanos,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,44\r\nCarl,Jenkinson,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nRob,Holding,0,0,2,85,3,0.4,13.4,2.0,0,13,1.6,0,0,0,0.1,45\r\nPierre-Emerick,Aubameyang,14,3,129,2033,31,335.1,616.2,883.0,24,484,183.3,5,1,3,16.8,108\r\nAlexandre,Lacazette,5,3,62,1275,18,263.8,297.0,628.0,6,206,119.1,3,0,5,2.0,93\r\nEdward,Nketiah,0,0,2,17,1,10.4,0.2,8.0,0,6,1.9,0,0,0,0.6,43\r\nBernd,Leno,0,0,89,2250,34,0.0,695.6,0.0,6,488,69.4,5,0,2,5.2,50\r\nMesut,\xc3\x96zil,0,2,37,1180,18,499.1,152.0,139.0,1,188,79.1,3,0,1,1.1,72\r\nHenrikh,Mkhitaryan,0,0,4,110,0,33.9,5.4,46.0,0,3,8.6,1,0,1,0.8,68\r\nGranit,Xhaka,0,1,40,1634,23,216.9,296.6,78.0,0,250,59.4,5,0,6,0.6,51\r\nLucas,Torreira,1,1,42,1343,20,189.2,267.0,199.0,0,232,65.7,3,0,4,1.3,47\r\nMohamed,Elneny,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.6,43\r\nMatteo,Guendouzi,0,2,43,1580,27,231.5,319.0,146.0,2,248,69.7,3,0,6,5.7,43\r\nDavid,Luiz Moreira Marinho,2,0,62,1915,30,89.1,496.2,169.0,9,337,75.6,4,1,4,4.8,57\r\nEmiliano,Mart\xc3\xadnez,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,43\r\nCalum,Chambers,1,1,42,1102,15,113.5,272.0,203.0,5,197,58.7,3,0,5,0.7,44\r\nDaniel,Ceballos Fern\xc3\xa1ndez,0,2,27,659,10,183.0,150.0,96.0,3,130,42.9,1,0,0,3.0,52\r\nC\xc3\xa9dric,Soares,0,1,43,1306,18,197.1,291.2,107.0,3,222,59.7,3,0,1,0.2,48\r\nNicolas,P\xc3\xa9p\xc3\xa9,3,3,63,1339,23,419.4,322.0,448.0,5,219,119.2,2,0,3,2.4,91\r\nReiss,Nelson,0,1,18,437,4,95.0,53.2,129.0,0,56,27.7,2,0,1,0.1,53\r\nJoseph,Willock,0,0,22,572,11,132.6,90.2,132.0,0,92,35.6,1,0,1,0.2,48\r\nGabriel Teodoro,Martinelli Silva,3,1,39,656,9,36.6,162.8,226.0,5,129,42.5,2,0,1,4.3,46\r\nKieran,Tierney,0,0,5,296,6,75.1,56.0,31.0,0,51,16.3,0,0,1,0.3,53\r\nBukayo,Saka,0,2,28,920,10,132.2,156.0,131.0,0,117,42.0,2,0,3,0.6,45\r\nEmile,Smith Rowe,0,0,4,96,0,6.3,9.8,0.0,0,13,1.6,1,0,0,0.0,43\r\nTyreece,John-Jules,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nPablo,Mar\xc3\xad,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,50\r\nAhmed,El Mohamady,0,1,19,701,24,218.9,170.2,46.0,5,154,43.6,1,0,0,0.9,42\r\nJames,Chester,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,43\r\nNeil,Taylor,0,0,17,793,19,31.6,115.8,27.0,0,113,17.5,2,0,2,0.2,43\r\nKortney,Hause,0,0,13,810,19,20.7,200.8,37.0,0,104,25.9,1,0,2,0.1,44\r\nJonathan,Kodjia,0,0,5,111,6,12.2,3.4,24.0,0,14,3.8,0,0,1,0.1,54\r\n\xc3\x98rjan,Nyland,0,0,3,177,8,0.0,57.0,0.0,0,34,5.8,0,0,0,0.2,43\r\nConor,Hourihane,3,2,50,843,23,251.9,242.0,178.0,6,199,67.0,2,0,3,0.2,57\r\nJack,Grealish,7,6,109,2063,43,820.2,647.2,582.0,14,445,204.7,4,0,6,25.1,67\r\nAnwar,El Ghazi,4,4,72,1550,35,401.0,337.2,522.0,0,221,126.0,4,0,3,0.9,55\r\nJohn,McGinn,3,2,61,1537,30,375.3,386.4,375.0,4,253,113.5,3,0,2,2.8,54\r\nAndre,Green,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,48\r\nBirkir,Bjarnason,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nKeinan,Davis,0,1,10,106,1,25.9,18.8,87.0,0,29,13.0,0,0,0,0.2,43\r\nHenri,Lansbury,0,0,11,189,6,27.2,13.4,13.0,0,34,5.5,0,0,0,0.4,44\r\nJos\xc3\xa9 Ignacio,Peleteiro Romallo,0,1,15,310,4,56.1,42.6,51.0,0,41,14.9,2,0,0,0.1,58\r\nTom,Heaton,0,0,59,1794,35,0.3,507.4,0.0,3,346,50.7,4,0,0,2.8,44\r\nDaniel,Drinkwater,0,0,5,258,9,7.8,9.8,8.0,0,25,2.5,0,0,1,0.6,44\r\nMatt,Targett,1,3,58,1418,26,346.0,368.0,111.0,10,312,82.6,3,0,3,0.9,44\r\nWesley,Moraes,5,1,67,1782,31,169.8,296.2,632.0,7,180,108.3,6,0,3,0.9,55\r\nJed,Steer,0,0,1,7,0,0.0,0.0,0.0,0,3,0.0,0,0,0,0.1,43\r\nTyrone,Mings,2,1,55,1822,36,73.0,529.2,108.0,5,345,71.1,3,0,5,2.8,45\r\nEzri,Konsa Ngoyo,0,2,29,1050,25,57.8,236.2,109.0,1,185,40.5,2,0,0,0.1,43\r\nBjorn,Engels,0,0,35,1266,25,21.6,276.8,38.0,4,223,33.9,3,0,1,0.4,44\r\nFr\xc3\xa9d\xc3\xa9ric,Guilbert,0,2,48,1628,27,190.4,374.4,46.0,2,276,61.3,4,0,5,0.5,44\r\nMahmoud Ahmed,Ibrahim Hassan,3,2,55,1233,21,248.8,269.6,556.0,2,160,107.2,3,1,2,1.1,52\r\nDouglas Luiz,Soares de Paulo,3,2,65,1441,31,176.7,341.8,306.0,5,263,82.5,5,0,4,4.0,44\r\nLovre,Kalinic,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,43\r\nMarvelous,Nakamba,0,0,31,1426,29,144.3,237.0,24.0,0,213,40.5,1,0,3,0.7,44\r\nIndiana,Vassilev,0,0,2,36,0,1.3,1.2,4.0,0,3,0.7,0,0,0,0.0,45\r\nJos\xc3\xa9,Reina,0,0,6,270,4,0.0,52.4,0.0,0,40,5.3,0,0,0,0.4,45\r\nMbwana,Samatta,1,0,8,90,2,23.3,41.2,72.0,2,28,13.7,0,0,0,0.3,60\r\nBorja,Gonz\xc3\xa1lez Tom\xc3\xa1s,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,55\r\nSteve,Cook,1,0,44,1650,31,37.8,434.0,110.0,5,280,58.4,3,1,3,0.2,50\r\nNathan,Ak\xc3\xa9,2,1,64,1744,27,67.9,463.6,242.0,6,360,77.3,3,0,1,6.6,48\r\nCharlie,Daniels,0,0,3,126,2,29.6,22.4,0.0,0,18,5.2,0,0,0,0.1,43\r\nChris,Mepham,1,0,26,901,19,16.5,268.6,136.0,2,161,42.2,1,0,1,0.7,43\r\nSimon,Francis,0,0,16,784,16,53.7,197.6,64.0,1,135,31.7,1,1,1,0.0,44\r\nAdam,Smith,0,1,37,1197,18,106.7,191.0,86.0,3,205,38.3,3,0,4,0.4,43\r\nLloyd,Kelly,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,44\r\nDiego,Rico,0,3,60,1703,25,384.9,411.8,73.0,5,322,87.3,5,0,6,11.2,43\r\nJack,Simpson,0,0,3,167,4,12.6,28.2,18.0,0,25,5.8,0,0,0,7.2,40\r\nCallum,Wilson,6,3,79,1986,37,306.9,287.4,538.0,6,240,112.4,3,0,6,4.8,74\r\nJoshua,King,3,3,58,1307,18,248.2,264.4,355.0,6,176,86.8,3,0,0,3.3,61\r\nDominic,Solanke,0,2,38,1136,24,159.9,99.0,385.0,0,68,64.4,1,0,1,0.3,52\r\nSam,Surridge,0,0,1,15,1,0.3,0.2,2.0,0,3,0.3,0,0,0,0.5,43\r\nAsmir,Begovic,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.7,42\r\nArtur,Boruc,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,43\r\nMark,Travers,0,0,1,90,3,0.0,15.2,0.0,0,9,1.5,0,0,0,0.2,42\r\nRyan,Fraser,1,4,63,1778,28,515.3,288.2,369.0,2,260,117.0,4,0,2,2.7,69\r\nDavid,Brooks,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,63\r\nJunior,Stanislas,0,0,3,106,2,33.1,16.0,19.0,0,16,6.8,0,0,0,0.0,59\r\nJordon,Ibe,0,0,2,48,1,5.4,6.8,0.0,0,10,1.2,0,0,0,0.1,46\r\nLewis,Cook,0,1,28,830,16,103.5,123.8,44.0,0,125,27.0,2,0,3,0.0,50\r\nAndrew,Surman,0,0,3,57,1,2.2,6.4,0.0,0,9,0.9,0,0,0,0.0,47\r\nDan,Gosling,2,1,33,700,11,66.1,199.6,159.0,1,108,42.4,1,0,1,0.1,49\r\nJefferson,Lerma,0,1,36,1773,29,127.1,260.0,62.0,2,233,44.6,3,1,9,0.1,48\r\nJack,Stacey,0,1,23,796,12,43.9,164.4,45.0,3,129,25.4,1,0,2,0.1,43\r\nPhilip,Billing,1,1,52,1802,27,158.5,455.2,244.0,5,271,85.9,5,0,7,0.2,50\r\nArnaut,Danjuma Groeneveld,0,1,18,405,6,39.8,45.4,120.0,0,55,20.5,2,0,0,0.0,58\r\nAaron,Ramsdale,0,1,87,2160,35,10.0,622.6,0.0,10,447,63.4,4,0,0,4.0,46\r\nHarry,Wilson,7,0,77,1288,25,193.7,353.4,500.0,7,254,104.7,2,0,1,2.2,58\r\nChristian,Saydee,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nGavin,Kilkenny,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nMihai-Alexandru,Dobre,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nShane,Duffy,1,0,33,981,14,19.4,219.6,60.0,0,167,29.8,2,0,1,0.9,48\r\nMart\xc3\xadn,Montoya,0,1,54,1536,24,266.1,288.8,169.0,3,263,72.6,5,0,3,0.6,44\r\nBernardo,Fernandes da Silva Junior,0,0,17,540,12,58.6,122.6,82.0,3,99,26.4,1,0,1,0.1,43\r\nLeon,Balogun,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,44\r\nGa\xc3\xabtan,Bong,0,0,3,57,3,27.9,16.0,6.0,0,15,5.0,0,0,0,0.1,42\r\nLewis,Dunk,2,3,81,2160,34,125.7,549.2,285.0,11,458,95.9,5,0,8,14.0,48\r\nMatthew,Clarke,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,44\r\nGlenn,Murray,1,0,26,603,8,44.5,54.0,173.0,0,46,26.8,2,0,0,0.7,54\r\nJ\xc3\xbcrgen,Locadia,0,0,3,85,1,1.3,3.2,30.0,0,5,3.3,1,0,0,0.1,52\r\nFlorin,Andone,1,0,5,71,2,11.3,45.0,21.0,1,20,7.6,0,1,0,0.4,47\r\nMathew,Ryan,0,0,91,2340,38,0.0,738.2,0.0,11,525,73.8,5,0,0,16.0,48\r\nDavid,Button,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,20.7,39\r\nPascal,Gro\xc3\x9f,2,5,69,1485,25,804.0,339.6,305.0,7,298,144.5,3,0,2,0.6,63\r\nAlireza,Jahanbakhsh,2,1,24,264,3,55.9,86.2,85.0,2,75,22.8,1,0,0,0.1,58\r\nJos\xc3\xa9 Heriberto,Izquierdo Mena,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,54\r\nAnthony,Knockaert,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,54\r\nYves,Bissouma,0,0,13,402,5,61.3,65.4,64.0,0,65,18.9,1,0,1,0.0,50\r\nDavy,Pr\xc3\xb6pper,1,2,58,2070,34,320.2,388.4,234.0,2,335,94.1,4,0,3,0.4,48\r\nSolomon,March,0,1,24,736,12,173.8,139.8,177.0,3,99,49.1,2,0,2,0.2,46\r\nBeram,Kayal,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,43\r\nDale,Stephens,0,1,47,1939,33,226.5,355.4,86.0,1,319,66.8,4,0,6,1.9,44\r\nLeandro,Trossard,3,5,69,1252,23,436.5,302.4,360.0,6,256,109.6,1,0,0,0.6,58\r\nDan,Burn,0,0,48,1877,30,238.4,392.4,98.0,0,317,72.8,5,0,3,0.2,45\r\nAdam,Webster,3,0,54,1745,31,115.3,452.2,196.0,5,329,76.6,2,0,3,0.7,44\r\nNeal,Maupay,7,2,88,1839,26,244.6,357.0,1123.0,12,246,172.2,5,0,3,2.2,59\r\nAaron,Mooy,2,1,57,1383,24,399.3,304.4,234.0,9,231,93.7,3,1,0,0.8,48\r\nAaron,Connolly,2,2,40,812,13,62.9,91.0,347.0,3,87,49.2,3,0,0,1.2,43\r\nTudor,Baluta,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,40\r\nSteven,Alzate,0,0,32,1173,18,212.7,193.6,201.0,0,175,60.8,3,0,1,0.1,45\r\nEzequiel,Schelotto,0,0,6,213,5,6.8,14.8,28.0,0,25,4.8,0,0,1,0.5,40\r\nTariq,Lamptey,0,0,1,31,0,0.0,0.0,0.0,0,8,0.0,0,0,0,0.1,40\r\nBen,Mee,0,2,74,2250,38,94.0,507.0,296.0,1,416,89.9,9,0,4,1.0,50\r\nJames,Tarkowski,1,2,86,2250,38,88.9,566.6,284.0,9,436,94.0,9,0,6,3.4,51\r\nMatthew,Lowton,0,1,41,1350,26,178.1,264.8,15.0,0,236,45.9,5,0,2,0.5,42\r\nPhil,Bardsley,0,0,29,900,12,61.7,149.8,47.0,0,154,25.8,4,0,2,0.2,43\r\nCharlie,Taylor,0,0,40,1015,9,158.5,179.0,9.0,2,190,34.8,5,0,2,1.0,42\r\nKevin,Long,0,0,1,2,0,0.1,0.0,0.0,0,2,0.0,0,0,0,0.1,43\r\nBen,Gibson,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,2.6,39\r\nAshley,Barnes,6,0,61,1350,21,85.1,226.2,474.0,6,161,75.9,8,0,4,2.3,61\r\nChris,Wood,10,1,98,1918,26,221.7,410.4,787.0,13,272,140.8,10,0,1,2.2,62\r\nMatej,Vydra,0,1,9,100,1,14.8,18.2,15.0,0,20,4.8,0,0,0,0.1,53\r\nNick,Pope,0,0,105,2250,38,30.3,595.4,2.0,12,517,62.7,9,0,0,15.1,47\r\nJoe,Hart,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,1.1,42\r\nJohann Berg,Gudmundsson,1,0,20,398,4,156.8,83.2,92.0,1,66,33.1,3,0,0,0.4,59\r\nDwight,McNeil,1,5,76,2169,36,591.1,380.2,261.0,1,331,123.2,10,0,4,0.5,60\r\nRobbie,Brady,1,2,28,394,10,87.2,103.4,86.0,0,99,27.7,1,0,1,0.0,55\r\nSteven,Defour,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,55\r\nJeff,Hendrick,2,1,57,1572,28,154.7,210.4,228.0,4,166,59.2,8,0,5,0.1,54\r\nAshley,Westwood,1,6,75,1980,27,499.6,365.4,102.0,7,343,96.7,9,0,8,0.5,54\r\nJack,Cork,0,0,53,2005,34,163.2,233.8,261.0,0,232,65.9,8,0,0,0.2,49\r\nAaron,Lennon,0,0,14,476,15,37.5,44.0,12.0,0,49,9.5,0,0,3,0.1,46\r\nErik,Pieters,0,3,42,1233,29,152.7,238.6,23.0,7,226,41.1,3,0,1,4.3,43\r\nJay,Rodriguez,4,0,50,1039,24,51.8,209.2,295.0,3,141,54.6,2,0,1,0.3,57\r\nBailey,Peacock-Farrell,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,44\r\nMace,Goodridge,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nAnthony,Driscoll-Glennon,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40\r\nAbd-Al-Ali Morakinyo Olaposi,Koiki,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40\r\nJosh,Brownhill,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,50\r\nMarcos,Alonso,1,3,47,588,4,149.0,178.2,115.0,5,181,44.1,4,0,3,2.0,60\r\nAntonio,R\xc3\xbcdiger,2,0,37,855,10,30.6,237.8,155.0,3,183,42.3,2,0,2,0.6,60\r\nC\xc3\xa9sar,Azpilicueta,2,3,78,2059,33,432.3,580.6,266.0,7,419,128.1,4,0,0,6.1,58\r\nEmerson,Palmieri dos Santos,0,0,18,1020,21,298.4,207.6,225.0,0,179,73.1,1,0,3,0.7,55\r\nAndreas,Christensen,0,0,20,1031,20,35.5,197.0,49.0,0,181,28.2,2,0,3,0.6,49\r\nDavide,Zappacosta,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,43\r\nOlivier,Giroud,0,0,7,190,5,55.6,14.6,64.0,0,16,13.3,1,0,0,1.0,66\r\nKepa,Arrizabalaga,0,0,63,2160,32,0.0,375.0,0.0,0,363,37.5,5,0,0,4.6,55\r\nWilly,Caballero,0,0,1,90,2,0.0,17.2,0.0,0,11,1.7,0,0,0,0.2,48\r\nWillian,Borges Da Silva,4,5,97,1724,18,716.6,478.8,592.0,14,417,178.8,7,0,2,4.6,71\r\nPedro,Rodr\xc3\xadguez Ledesma,0,0,12,383,8,120.1,71.0,170.0,0,45,36.2,1,0,0,1.1,68\r\nRuben,Loftus-Cheek,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,63\r\nCallum,Hudson-Odoi,1,4,45,768,12,310.5,204.8,323.0,3,172,83.6,2,0,1,0.9,53\r\nRoss,Barkley,0,0,15,478,7,158.4,89.6,205.0,0,60,45.4,2,0,0,1.2,56\r\nJorge Luiz,Frello Filho,4,3,76,1766,27,327.4,488.0,156.0,9,425,97.5,4,0,9,4.4,49\r\nN'Golo,Kant\xc3\xa9,3,0,48,1372,20,369.2,368.0,201.0,2,239,94.0,2,0,3,4.1,50\r\nEthan,Ampadu,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,44\r\nChristian,Pulisic,5,3,70,1069,19,271.9,335.6,719.0,5,217,132.7,3,0,0,3.6,69\r\nMateo,Kovacic,1,3,50,1408,24,326.0,360.6,141.0,4,332,82.6,2,0,7,0.9,53\r\nKurt,Zouma,0,0,37,1668,26,30.3,376.0,127.0,1,281,52.9,3,0,3,1.6,47\r\nTammy,Abraham,13,5,130,1911,26,265.4,576.2,1042.0,20,395,187.5,7,0,2,22.8,77\r\nMichy,Batshuayi,1,2,25,139,6,39.0,61.8,165.0,1,58,26.1,0,0,0,0.5,66\r\nRobert Kenedy,Nunes do Nascimento,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,52\r\nMason,Mount,5,5,99,1979,28,612.2,461.4,738.0,8,359,181.3,7,0,3,15.1,61\r\nReece,James,0,2,40,765,9,176.6,190.6,85.0,5,216,45.3,3,0,1,0.7,50\r\nFikayo,Tomori,1,0,47,1228,16,65.4,318.2,77.0,7,255,46.3,4,0,3,2.1,44\r\nBilly,Gilmour,0,0,2,9,1,12.6,2.8,0.0,0,5,1.5,0,0,0,0.0,45\r\nAddji Keaninkin Marc-Israel,Guehi,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,40\r\nPatrick,van Aanholt,2,0,58,1622,24,258.3,298.2,172.0,3,297,72.9,4,0,0,4.2,55\r\nJames,Tomkins,1,1,48,1582,23,27.7,384.0,121.0,4,260,53.3,3,0,5,0.6,50\r\nMamadou,Sakho,0,0,7,465,8,13.2,86.0,6.0,0,69,10.6,0,1,0,0.1,50\r\nJoel,Ward,0,1,42,1300,18,64.0,237.8,30.0,5,215,33.2,3,0,3,1.0,43\r\nScott,Dann,0,1,16,364,3,10.9,89.2,71.0,0,76,17.1,1,0,0,0.1,43\r\nMartin,Kelly,0,1,64,1547,16,96.5,305.4,15.0,4,288,41.7,6,0,0,25.4,43\r\nChristian,Benteke,1,0,26,652,11,148.0,130.6,351.0,1,85,62.8,1,0,2,0.5,57\r\nConnor,Wickham,1,1,15,90,2,34.5,59.8,64.0,2,48,15.8,0,0,0,2.0,44\r\nVicente,Guaita,0,0,89,2160,28,0.0,578.0,0.0,10,431,57.8,6,0,1,2.1,51\r\nWayne,Hennessey,0,0,6,180,4,0.0,87.4,0.0,0,42,8.7,0,0,0,0.6,43\r\nWilfried,Zaha,3,5,87,2275,32,426.7,439.2,737.0,4,262,160.5,5,0,3,9.5,68\r\nLuka,Milivojevic,2,1,61,1965,26,436.3,356.6,151.0,7,296,94.4,6,0,9,1.9,67\r\nAndros,Townsend,1,1,34,791,12,132.8,167.8,70.0,0,141,37.1,3,0,0,1.0,56\r\nMax,Meyer,0,0,18,541,7,27.4,49.8,94.0,0,43,16.9,1,0,1,0.1,52\r\nJeffrey,Schlupp,2,1,40,856,12,95.3,198.0,233.0,3,121,52.7,4,0,2,0.1,54\r\nJames,McArthur,0,3,64,2177,25,292.6,416.6,337.0,2,302,104.8,7,0,4,0.6,52\r\nCheikhou,Kouyat\xc3\xa9,1,2,64,1714,23,138.3,253.0,220.0,4,219,60.9,6,0,1,0.3,49\r\nLuke,Dreher,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,43\r\nCenk,Tosun,2,0,22,458,6,52.6,82.6,227.0,1,76,35.8,2,0,0,0.2,57\r\nJames,McCarthy,0,0,25,945,16,102.2,149.8,53.0,0,117,30.6,0,0,5,0.7,43\r\nJordan,Ayew,6,1,90,2112,27,298.1,385.2,566.0,17,297,124.5,8,0,4,7.8,50\r\nGary,Cahill,0,1,41,1530,26,37.5,328.2,194.0,3,266,56.3,3,0,1,1.2,44\r\nV\xc3\xadctor,Camarasa,0,0,1,5,0,0.1,0.2,0.0,0,3,0.0,0,0,0,0.2,45\r\nJairo,Riedewald,0,0,13,562,7,38.2,89.8,24.0,0,83,15.2,0,0,0,0.0,45\r\nStephen,Henderson,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.4,40\r\nSam,Woods,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40\r\nTyrick,Mitchell,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40\r\nBrandon,Pierrick,0,0,1,7,0,21.0,4.4,2.0,0,5,2.7,0,0,0,0.0,45\r\nJames,Daly,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nNya,Kirby,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nGiovanni,McGregor,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nAlex,Iwobi,1,0,37,1103,23,267.3,184.2,283.0,2,162,73.5,1,0,0,0.9,56\r\nLucas,Digne,0,5,83,2151,36,881.5,515.2,229.0,12,459,162.7,6,0,2,13.1,58\r\nYerry,Mina,2,0,69,1995,33,65.2,459.2,385.0,8,359,90.9,5,0,3,2.2,53\r\nMichael,Keane,1,0,53,1566,27,31.6,351.2,152.0,3,277,53.5,4,0,0,1.9,52\r\nSeamus,Coleman,0,1,33,1162,20,122.2,206.8,132.0,2,203,46.2,3,1,3,1.1,53\r\nLeighton,Baines,0,1,8,152,2,23.4,36.4,3.0,0,38,6.3,0,0,0,0.2,49\r\nDominic,Calvert-Lewin,11,1,96,1649,27,197.9,446.4,857.0,13,332,149.6,5,0,6,11.2,61\r\nJordan,Pickford,0,0,78,2340,38,3.0,515.2,0.0,3,425,51.6,6,0,1,6.9,53\r\nMaarten,Stekelenburg,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,7.3,40\r\nRicharlison,de Andrade,9,5,123,2082,34,359.7,626.2,872.0,13,395,186.0,6,0,4,8.5,81\r\nGylfi,Sigurdsson,1,3,64,1722,29,624.3,313.4,348.0,4,290,128.5,5,0,2,2.4,73\r\nBernard,An\xc3\xadcio Caldeira Duarte,3,2,57,914,8,242.1,253.4,216.0,6,182,70.9,7,0,2,0.7,64\r\nTheo,Walcott,1,3,46,951,11,208.7,148.4,449.0,1,127,80.8,3,0,1,0.4,62\r\nTom,Davies,1,1,40,1218,21,82.2,174.2,201.0,3,145,45.9,3,0,6,0.1,53\r\nAdemola,Lookman,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,50\r\nIdrissa,Gueye,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,50\r\nMorgan,Schneiderlin,0,0,18,940,17,77.1,137.8,32.0,0,133,24.9,1,1,3,0.6,44\r\nFabian,Delph,0,0,23,1106,21,134.4,166.8,16.0,2,187,31.7,2,1,3,0.2,53\r\nAndr\xc3\xa9 Filipe,Tavares Gomes,0,0,13,584,8,90.4,55.0,13.0,0,71,15.8,2,0,3,0.3,52\r\nLewis,Gibson,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,43\r\nMason,Holgate,0,4,53,1462,24,50.6,348.0,148.0,5,303,54.8,3,0,3,2.8,45\r\nJonas,L\xc3\xb6ssl,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.3,43\r\nMoise,Kean,1,2,37,622,12,97.9,95.0,298.0,3,88,48.6,1,0,0,1.5,64\r\nJean-Philippe,Gbamin,0,0,4,135,0,6.3,20.0,0.0,0,14,2.6,1,0,0,0.0,48\r\nDjibril,Sidib\xc3\xa9,0,4,62,1396,21,293.3,371.0,95.0,9,319,75.9,4,0,2,1.7,53\r\nBeni,Baningime,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,45\r\nAnthony,Gordon,0,0,1,45,0,7.4,0.0,14.0,0,2,2.0,0,0,0,0.0,45\r\nOumar,Niasse,0,0,3,19,2,1.8,7.0,0.0,0,1,0.9,0,0,0,0.0,45\r\nRhu-endly,Martina,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40\r\nRicardo Domingos,Barbosa Pereira,3,2,107,2160,25,350.0,663.8,210.0,11,497,122.3,8,0,1,13.2,63\r\nBenjamin,Chilwell,2,3,85,1789,21,393.7,411.6,149.0,3,389,95.5,7,0,1,9.0,56\r\nJonny,Evans,1,2,90,2214,26,47.2,537.2,244.0,7,494,82.9,8,0,4,6.0,52\r\nChristian,Fuchs,0,0,22,544,5,47.0,113.2,18.0,2,101,17.8,2,0,0,0.3,43\r\n\xc3\x87aglar,S\xc3\xb6y\xc3\xbcnc\xc3\xbc,1,1,86,2160,25,54.5,564.2,158.0,8,501,77.9,8,0,4,15.9,50\r\nWes,Morgan,0,0,8,159,1,0.7,45.8,36.0,0,32,8.2,0,0,0,0.6,41\r\nJamie,Vardy,17,6,152,2011,24,222.9,751.2,898.0,25,559,186.9,7,0,2,37.3,98\r\nKelechi,Iheanacho,3,4,40,386,6,124.9,180.4,299.0,5,142,60.6,1,0,1,0.4,57\r\nKasper,Schmeichel,0,0,92,2250,26,10.0,558.8,0.0,3,450,56.9,8,0,1,13.8,54\r\nEldin,Jakupovic,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,42\r\nDanny,Ward,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.2,43\r\nJames,Maddison,6,5,110,2039,23,1001.3,560.8,586.0,14,444,214.9,7,0,3,21.7,75\r\nHarvey,Barnes,4,7,87,1390,14,364.3,352.4,613.0,5,256,133.1,5,0,0,2.3,60\r\nRachid,Ghezzal,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,52\r\nMarc,Albrighton,0,1,15,352,7,132.8,68.4,50.0,0,76,25.1,0,0,1,0.2,51\r\nDemarai,Gray,1,2,24,409,4,114.3,109.2,156.0,0,80,37.8,0,0,1,0.2,51\r\nWilfred,Ndidi,2,1,63,1786,18,187.9,474.8,146.0,5,332,80.9,8,0,3,1.8,50\r\nMatty,James,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.1,43\r\nDaniel,Amartey,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.3,43\r\nNampalys,Mendy,0,0,6,193,3,34.2,36.4,9.0,0,49,8.0,0,0,0,0.9,43\r\nHamza,Choudhury,1,1,27,636,10,62.8,149.2,79.0,0,127,29.1,1,0,2,0.9,43\r\nAyoze,P\xc3\xa9rez,7,5,104,1433,16,320.9,455.6,559.0,9,320,133.8,6,0,0,9.3,62\r\nRyan,Bennett,0,0,21,603,9,33.7,113.6,16.0,0,110,16.3,2,0,2,0.3,48\r\nJames,Justin,0,1,7,110,1,29.5,45.2,6.0,0,30,8.0,0,0,0,0.1,47\r\nYouri,Tielemans,3,5,88,1953,23,518.3,396.2,347.0,5,360,126.4,8,0,1,4.3,62\r\nAndy,King,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.3,43\r\nDennis,Praet,1,3,42,715,8,111.7,152.4,146.0,3,165,40.8,1,0,0,0.1,53\r\nFilip,Benkovic,0,0,0,0,0,0.0,0.0,0.0,0,0,0.0,0,0,0,0.0,40\r\nAndrew,Robertson,1,6,123,2173,15,553.5,545.2,246.0,12,568,134.6,10,0,1,20.6,70\r\nTrent,Alexander-Arnold,2,12,146,2189,15,1010.6,731.6,300.0,14,636,204.2,10,0,4,43.5,77\r\nVirgil,van Dijk,4,0,127,2250,15,65.3,643.4,268.0,11,548,97.6,11,0,1,44.7,65\r\nJoseph,Gomez,0,0,65,1007,2,67.7,216.0,0.0,5,277,28.4,9,0,3,5.1,53\r\nJoel,Matip,1,0,32,630,5,20.9,192.4,35.0,4,141,25.0,2,0,0,1.2,52\r\nDejan,Lovren,0,1,16,669,8,20.7,172.0,52.0,0,130,2

In [421]:
#Looks a bit messy! Lets clean it up quickly and have a look at the first 5 names, notice they are ordered by team.
address = pd.read_csv(io.StringIO(read_data.decode('utf-8')))
print(address.head())

  first_name       second_name  goals_scored  assists  total_points  minutes  \
0   Shkodran           Mustafi             0        2            19      440
1     Héctor          Bellerín             1        0            17      442
2       Sead         Kolasinac             0        2            34     1086
3    Ainsley    Maitland-Niles             0        2            36     1210
4   Sokratis  Papastathopoulos             2        0            52     1606

   goals_conceded  creativity  influence  threat  bonus  bps  ict_index  \
0               7        13.2      128.8    79.0      1  101       22.2
1               8        28.1      103.8    28.0      3   81       16.1
2              18       156.3      190.0    67.0      1  219       41.2
3              19       155.4      261.8    37.0      3  216       44.9
4              25        31.8      431.6   106.0      5  286       57.1

   clean_sheets  red_cards  yellow_cards  selected_by_percent  now_cost
0             1          0             0                  0.3        51
1             1          0             2                  0.8        54
2             2          0             3                  0.5        52
3             3          1             3                  2.5        46
4             3          0             5                  1.4        49

In [422]:
#Removing any players who have not played a single minute this season.
address = address[address.minutes != 0]
address

,first_name,second_name,goals_scored,assists,total_points,minutes,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost
0,Shkodran,Mustafi,0,2,19,440,7,13.2,128.8,79.0,1,101,22.2,1,0,0,0.3,51
1,Héctor,Bellerín,1,0,17,442,8,28.1,103.8,28.0,3,81,16.1,1,0,2,0.8,54
2,Sead,Kolasinac,0,2,34,1086,18,156.3,190.0,67.0,1,219,41.2,2,0,3,0.5,52
3,Ainsley,Maitland-Niles,0,2,36,1210,19,155.4,261.8,37.0,3,216,44.9,3,1,3,2.5,46
4,Sokratis,Papastathopoulos,2,0,52,1606,25,31.8,431.6,106.0,5,286,57.1,3,0,5,1.4,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,Leander,Dendoncker,2,0,62,1998,29,93.1,389.2,190.0,6,309,67.2,4,0,2,9.8,44
612,Jesús,Vallejo Lázaro,0,0,1,162,6,7.0,35.6,0.0,0,22,4.3,0,0,1,0.2,46
613,Patrick,Cutrone,2,0,23,292,6,35.6,85.2,155.0,0,69,27.5,1,0,0,0.5,55
614,Pedro,Lomba Neto,2,2,37,617,8,132.9,147.4,190.0,0,126,46.9,0,0,2,0.2,50
622,Daniel,Castelo Podence,0,0,1,14,0,15.1,6.4,18.0,0,7,4.0,0,0,0,0.0,55

In [423]:
#I will remove total points earned and minutes played, and then try to predict the points per minute score of each player using what is left.
#This should work well as a binary classification problem because much of this information will be highly indicative of how many points a player has earned.
#If a player has scored a lot of goals, he likely has a lot of points etc.

In [424]:
#Calculating the points per minute.
I = range(0,len(address))
J = list(I)
for i in I:
    J[i] = address.iloc[i]['total_points'] / address.iloc[i]['minutes']
address.insert(18, 'points_per_minute', J)
print(address.head())

  first_name       second_name  goals_scored  assists  total_points  minutes  \
0   Shkodran           Mustafi             0        2            19      440
1     Héctor          Bellerín             1        0            17      442
2       Sead         Kolasinac             0        2            34     1086
3    Ainsley    Maitland-Niles             0        2            36     1210
4   Sokratis  Papastathopoulos             2        0            52     1606

   goals_conceded  creativity  influence  threat  bonus  bps  ict_index  \
0               7        13.2      128.8    79.0      1  101       22.2
1               8        28.1      103.8    28.0      3   81       16.1
2              18       156.3      190.0    67.0      1  219       41.2
3              19       155.4      261.8    37.0      3  216       44.9
4              25        31.8      431.6   106.0      5  286       57.1

   clean_sheets  red_cards  yellow_cards  selected_by_percent  now_cost  \
0             1          0             0                  0.3        51
1             1          0             2                  0.8        54
2             2          0             3                  0.5        52
3             3          1             3                  2.5        46
4             3          0             5                  1.4        49

   points_per_minute
0           0.043182
1           0.038462
2           0.031308
3           0.029752
4           0.032379

In [425]:
#we now have a column to our dataset containing the points per minute score of each player, now lets find the mean.
total_ppm = address['points_per_minute'].sum()

avg_ppm = total_ppm / len(address)
        
print(avg_ppm)
#

0.05035836240509932

In [426]:
#Now lets add a column telling us if a player is above or below average.
#Call this column 'T' and enter 0 if the player is below average, and 1 if he is above or equal to the average.
K = range(0,len(address))
T = list(K)
for i in K:
    if address.iloc[i]['points_per_minute'] / avg_ppm >= 1 :
        T[i] = 1
    else:
        T[i] = 0
address.insert(19, 'T', T)

print(address.head())
#

  first_name       second_name  goals_scored  assists  total_points  minutes  \
0   Shkodran           Mustafi             0        2            19      440
1     Héctor          Bellerín             1        0            17      442
2       Sead         Kolasinac             0        2            34     1086
3    Ainsley    Maitland-Niles             0        2            36     1210
4   Sokratis  Papastathopoulos             2        0            52     1606

   goals_conceded  creativity  influence  threat  bonus  bps  ict_index  \
0               7        13.2      128.8    79.0      1  101       22.2
1               8        28.1      103.8    28.0      3   81       16.1
2              18       156.3      190.0    67.0      1  219       41.2
3              19       155.4      261.8    37.0      3  216       44.9
4              25        31.8      431.6   106.0      5  286       57.1

   clean_sheets  red_cards  yellow_cards  selected_by_percent  now_cost  \
0             1          0             0                  0.3        51
1             1          0             2                  0.8        54
2             2          0             3                  0.5        52
3             3          1             3                  2.5        46
4             3          0             5                  1.4        49

   points_per_minute  T
0           0.043182  0
1           0.038462  0
2           0.031308  0
3           0.029752  0
4           0.032379  0

In [427]:
#Now lets remove the relevent columns, so the dataset contains no actual data on points earned.
address_1 = address.drop(['total_points', 'minutes', 'points_per_minute', 'T'], 1)
print(address_1.head())

#This is the dataset we use to make the model, T is our target. This cell is mainly just for visual clarity.
#

  first_name       second_name  goals_scored  assists  goals_conceded  \
0   Shkodran           Mustafi             0        2               7
1     Héctor          Bellerín             1        0               8
2       Sead         Kolasinac             0        2              18
3    Ainsley    Maitland-Niles             0        2              19
4   Sokratis  Papastathopoulos             2        0              25

   creativity  influence  threat  bonus  bps  ict_index  clean_sheets  \
0        13.2      128.8    79.0      1  101       22.2             1
1        28.1      103.8    28.0      3   81       16.1             1
2       156.3      190.0    67.0      1  219       41.2             2
3       155.4      261.8    37.0      3  216       44.9             3
4        31.8      431.6   106.0      5  286       57.1             3

   red_cards  yellow_cards  selected_by_percent  now_cost
0          0             0                  0.3        51
1          0             2                  0.8        54
2          0             3                  0.5        52
3          1             3                  2.5        46
4          0             5                  1.4        49

In [428]:
#spliting the data into training and testing, roughly 80% will be training, 20% testing.

msk = np.random.rand(len(address)) < 0.8

train = address[msk]   #Splitting the whole data
test = address[~msk]


#removing the unwanted columns.
#We drop the names because they are strings and the model cant use them, we can use the index to identify players later
data_train = train.drop(['total_points', 'minutes','points_per_minute', 'T','first_name', 'second_name'], 1)   
data_test = test.drop(['total_points', 'minutes','points_per_minute', 'T', 'first_name', 'second_name'], 1)

T_train_1 = address[msk][['T']]
T_test_1 = address[~msk][['T']]
#Need these to be a series format in order for use of LogisticRegression().
T_train = T_train_1['T']
T_test = T_test_1['T']

In [429]:
#Testing our data is formatted correctly:
type(T_train)

pandas.core.series.Series

In [430]:
#It is a series as required. Now lets see how many of our samples are reserved for testing.
len(data_test)

98

In [431]:
#Great! now lets have a look at the dataset we have created for training:
data_train

,goals_scored,assists,goals_conceded,creativity,influence,threat,bonus,bps,ict_index,clean_sheets,red_cards,yellow_cards,selected_by_percent,now_cost
0,0,2,7,13.2,128.8,79.0,1,101,22.2,1,0,0,0.3,51
1,1,0,8,28.1,103.8,28.0,3,81,16.1,1,0,2,0.8,54
2,0,2,18,156.3,190.0,67.0,1,219,41.2,2,0,3,0.5,52
3,0,2,19,155.4,261.8,37.0,3,216,44.9,3,1,3,2.5,46
4,2,0,25,31.8,431.6,106.0,5,286,57.1,3,0,5,1.4,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,0,1,2,43.5,6.2,12.0,0,31,6.2,0,0,0,0.1,47
608,4,7,28,555.7,588.0,454.0,14,437,159.9,4,0,0,19.9,58
612,0,0,6,7.0,35.6,0.0,0,22,4.3,0,0,1,0.2,46
613,2,0,6,35.6,85.2,155.0,0,69,27.5,1,0,0,0.5,55
622,0,0,0,15.1,6.4,18.0,0,7,4.0,0,0,0,0.0,55

# Logistic Regression Model

In [432]:
#I think we are ready to import the model and get going.
from sklearn.linear_model import LogisticRegression
log_reg_model = LogisticRegression()
log_reg_model.fit(data_train,T_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [433]:
#Testing the model:

log_reg_model_predictions = log_reg_model.predict(data_test)

#Lets have a look at the predictions against the real data:
print('T')
print(T_test)
print()
print('Predicted T')
print(log_reg_model_predictions)

T
11     0
39     0
41     1
47     1
55     0
      ..
581    0
596    0
600    1
611    0
614    1
Name: T, Length: 98, dtype: int64

Predicted T
[1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0
 1 1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0
 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1]

In [434]:
#By inspection we can see already that the first five players have been predicted correctly.
#We can use the following metrics to test the model mathematically.

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

#Checking the precision of our model:

print(classification_report(T_test, log_reg_model_predictions))

              precision    recall  f1-score   support

           0       0.88      0.93      0.91        72
           1       0.77      0.65      0.71        26

    accuracy                           0.86        98
   macro avg       0.83      0.79      0.81        98
weighted avg       0.85      0.86      0.85        98

In [435]:
#The model predicts to an accuracy of 85%! This is a decent score, now lets make a function to make a prediction for an individual.

In [436]:
#For this, lets train the model on the full data set, to hopefully improve our accuracy a little more.
full_data = address.drop(['total_points', 'minutes','first_name','points_per_minute', 'T', 'second_name'], 1)
full_predictions = log_reg_model.predict(full_data)
#Lets have a look at them.
print(full_predictions)

[1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1
 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0
 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0
 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1]

In [437]:
#Notice the long string of '1's in about the middle row, I suspect that may be where we reach the Liverpool team.

In [457]:
#Lets write the function:
def performance_LR(fn, sn):
    i = address.loc[address['first_name'] == fn].index[0]
    j = address.loc[address['second_name'] == sn].index[0]    #Finding the index from the name.
    if i == j:
        if full_predictions[i] == 1:       #Referring to the above.
            print('Player has above average points per minute')
        else:
            print('Player has below average points per minute')
    else:
        print('First name index does not match the last, likely there are multiple players with that name.')

In [458]:
#Lets test it using the first player, Mustafi, who somehow has an above average points per minute score.
performance_LR('Shkodran', 'Mustafi')

Player has above average points per minute

In [459]:
#At least the model can predict correctly, lets try another one:
performance_LR('Sead', 'Kolasinac')

Player has below average points per minute

In [441]:
#Another correct prediction!

# K Nearest Neighbours

In [442]:
#Now we will use a knn simple predictive model, again imported from sklearn.

from sklearn.neighbors import KNeighborsClassifier

#For simplicity we will start with K=1.
knn_1 = KNeighborsClassifier(n_neighbors = 1)

In [443]:
#We can use the same split as before:
knn_1.fit(data_train,T_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [444]:
#Lets test it on Mustafi again.
#Extracting his row as a new dataframe.
mustafi_test = address.loc[address['second_name'] == 'Mustafi']
#Removing the required columns.
mustafi_test_1 = mustafi_test.drop(['total_points', 'minutes', 'first_name', 'second_name', 'points_per_minute', 'T'], 1) 
#Calling the model, should return '1'.
knn_1.predict(mustafi_test_1)[0]

0

In [445]:
#Good, now lets use the testing set.
knn_1_predictions = knn_1.predict(data_test)
print(knn_1_predictions)

[1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0
 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0
 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1]

In [446]:
#Comparing by inspection again, to the actual data:
print(T_test)

11     0
39     0
41     1
47     1
55     0
      ..
581    0
596    0
600    1
611    0
614    1
Name: T, Length: 98, dtype: int64

In [447]:
#Again we see the first 5 values are predicted correctly. Lets evaluate using the classification report again.
print(classification_report(T_test, knn_1_predictions))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85        72
           1       0.58      0.69      0.63        26

    accuracy                           0.79        98
   macro avg       0.73      0.76      0.74        98
weighted avg       0.80      0.79      0.79        98

In [448]:
#This is less accurate than the logistic regression model, but still not too bad with almost 80% accuracy.
#Lets see what happens if we try again with k = 3.

knn_3 = KNeighborsClassifier(n_neighbors = 3)

knn_3.fit(data_train,T_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [449]:
#Mustafi test:
mustafi_test = address.loc[address['second_name'] == 'Mustafi']
#Removing the required columns.
mustafi_test_1 = mustafi_test.drop(['total_points', 'minutes','first_name', 'second_name', 'points_per_minute', 'T'], 1) 
#Calling the model, should return '1'.
knn_3.predict(mustafi_test_1)[0]

0

In [450]:
knn_3_predictions = knn_3.predict(data_test)
print(knn_3_predictions)

[0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0
 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0
 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]

In [451]:
print(classification_report(T_test, knn_3_predictions))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        72
           1       0.69      0.69      0.69        26

    accuracy                           0.84        98
   macro avg       0.79      0.79      0.79        98
weighted avg       0.84      0.84      0.84        98

In [452]:
#Our accuracy has improved marginally, lets try k =5.
knn_5 = KNeighborsClassifier(n_neighbors = 5)

knn_5.fit(data_train,T_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [453]:
knn_5_predictions = knn_5.predict(data_test)
print(classification_report(T_test, knn_5_predictions))

              precision    recall  f1-score   support

           0       0.89      0.88      0.88        72
           1       0.67      0.69      0.68        26

    accuracy                           0.83        98
   macro avg       0.78      0.78      0.78        98
weighted avg       0.83      0.83      0.83        98

In [ ]:
#This time we are less accurate, lets say k = 3 was a good model.